ran = [ "Thanks!"
	, "take care of your health guys))"
	, "there are other ways, but why not 😄"
	, "it's good to chat it up in here and see how it's going"
	, "I want that coffee cup the emoji has","Are you from Indonesia?"
	, "Sure thing!"
	, "Yep,the best way to do it!"
	, "This project is one of the few that checks all the boxes for success"
	, "sup everyone where are you guys from SF bay area here","Doing great friend, how are you?"
	, "its awesome project"
	, "best community ever guys )"
	, "Good wbu"
	, "i mean the commuity is insane"
	, "So stoked for this man cannot wait for the drop","i wish you the best bro"
	, "What do you guys think about this project?"
	, "thank you my friend"
	, "Don t get worried… we will make it"
	, "The team is always there to watch what we're doing))","Pls don’t bing bing I’m getting scared"
	, "we all fam here , lets grinding here too, haha"
	, "This is the NFT project i really wanna be in on))"
	, "Everyone go to see you"
	, "Everyone continue grinding for this! This is next level project hehe","griding hard, as usual))"
	, "enjoying the vibes in here"
	, "Fine guys hanks for it, ya'll look very welcoming in here!!"
	, "We love this community"
	, "You do not find the happy life. You make it"
	, "So we have to be more active innit?"
	, "time is money people don’t sleep on this project let’s get that whitelist!"
	, "Meditation can help to calm our mind down"
	, "we can do this brothers!!"
	, "hoping that happens to me one day lol)"
	, "I think I should take it xd"
	, "cant wait man!"
	, "same bro))"
	, "drink a coffee folk and keep grinding"
	, "we are happy to have you here bro!","what do you think about the mint price, huh?"
	, "bless me lmaoooo"
	, "dude, team is working hard as well"
	, "Let us keep spreading love and positivity in this community"
	, "need this projectt"
	, "Ready to go all the way and be left without fingers","like you cant imagine how hyped i am haha"
	, "gn bro rest well"
	, "I hope we will get all wl"
	, "Lets fuck*** go!"
	, "lets hustle dude, thats crazy))"
	, "Hey guys can you point me in the direction of some good gaming cryptos (Serious question) btw","I’m down like the floor on crap NFTs lolol"
	, "working on a weekend like usual(("
	, "can't stop chat rn!"
	, "cool project btw"
	, "I need to get whitelisted.."
	, "Anyone here new to discord?","no sleep for me"
	, "We need u now the most!))"
	, "Where are you from?"
	, "hmmm, sounds good"
	, "okay lets find out"
	, "ahha, nice joke btw"
	, "okaaaay let's go, i like this meme))"
	, "i hope this project will earn me good money"
	, "want to take some grands from this project))"
	, "Ive made some tech analysis, and i have found out that this project is realllllly prospective..."
	, "work work and hard work again"
	, "someone knows artemus dolgin?, he ispires me to live))"
	, "I still have to earn some points to get vitelisted))"
	, "btw how are u feeling today?"
	, "How can i get vitelisted?????? faster???"
	, "should i write any articles to be whitlisted ?"
	, "okay thx for it))"
	, "wish yall good day))"
	, "commone mates, lets hustle))"
	, "Iam from Berlin, this is nice city))"
	, "where are you from guys?","we are gunna make it"
	, "WAGMI mates"
	, "definitely gonna make it boys"
	, "okay bro you are right"
	, "chat is so fast xd"
	, "i am gonna invite some friends here"
	, "thanks for the opportunity","so fast i can't even read"
	, "wagmi wagmi LOL))"
	, "go grind guys"
	, "working on a weekend like usual(("
	, "on the way to wl shiiish"
	, "ONM TO WL"
	, "gonna eat some food","LFG for sure"
	, "man it's awesome"
	, "yo sup boys"
	, "this def is a diamond"
	, "this is absolytely gem))"
	, "good job boys"
	, "working a lot "
	, "let's go guys never stop"
	, "i'm sleepy but grinding"
	, "grind never stops"
	, "who's still sleeping on this project? lol"
	, "yikes the chat is amazing"
	, "thanks for help"
	, "no problem bro"
	, "how y'all doin","i'm good hbu"
	, "we good we good"
	, "never stop just work"
	, "who stops ngmi"
	, "keep the work guys"
	, "wow so many people here"
	, "wanna get that wl))"
	, "don't stop don't stop","chill guys you are too fast"
	, "im sure this is cool project"
	, "it's good to be here"
	, "The more we invite the stronger the foundation of this project will be. Keep inviting!"
	, "Share your reactions guys"
	, "Have a good day, guys"
	, "We need real holder and real people"
	, "Let’s enjoy our time keep it up"
	, "Excited for this project","how is your family doing"
	, "Feel free to ask any question and we will try to help one another"
	, "Keeep expanding our community fam."
	, "Go to invite tab and type in “-invites”"
	, "Hopefully it is 👍"
	, "Let’s go to the moon🚀"
	, "Looks like a really good roadmap"
	, "Guys don’t forget to help each other we are all here for one purpose"
	, "never stop not with this project trust me","Huge project"
	, "the chat is active all the time"
	, "Excited for this project"
	, "Wishing everyone a successful journey"
	, "Love the Project is amazing"
	, "artwork is dope","just keep going no matter what"
	, "This is the NFT project you wanna be in on"
	, "Gang gang💪🏾💪🏾"
	, "drink a coffee an keep grinding"
	, "Comment 🔥🔥 if you ready","Moon incoming"
	, "I think we couldn’t even got into the stadium since this is really a huge community"
	, "patience and determination"
	, "All the way up"
	, "A little tired of sitting already("
	, "we can make it.."
	, "Keep it going"
	, "i mean the best you can do is just being avtive in here and support the ppl"
	, "We going crazy in here crazy chat"
	, "The energy the mindset I love it I want please WL"
	, "best nft collection"
	, "We got this guys"
	, "We re waiting"
	, "Wuhooo excited"
	, "Want to beeee WL 🙂"
	, "wl wl incoming"
	, "Would be nice to get another sneak peek for the weekend"
	, "grind go to other chats"
	, "maybe better chat here"
	, "Man we are truly blessed"
	, "Lets go brothers make it happen"
	, "Happy new year! and welcome budddy","Hope i have this good luck"
	, "I love this project"
	, "stay active and mods will find you bro"
	, "Goodluck guys!"
	, "This is a good news to us"
	, "Yeah bro this so hype","Good job guys"
	, "it is really good"
	, "Great project, admins are useful and helpful"
	, "Hope all will be fine"
	, "2022 we going up guys"
	, "dont know bro wbu?"
	, "This 2022 will be mine)"
	, "What rank are you?"
	, "how long does it  take to get 5 lvl?"
	, "Come on guys let’s do it"
	, "maybe better chat here"
	, "I’m feeling good , how you feelin ?"
	, "Excitingggg and firee"
	, "many spots left, dont give up"
	, "Where's everyone from?","How are you today ?"
	, "Would be nice to know how many WL spot there are in total"
	, "im excited to have this nft i hope i get WL fastttttt"
	, "It would be great really","I believe in this project"
	, "Good to be here! It's like smelling fresh air !"
	, "That what we need cheer up"
	, "Ye my friend only running for today"
	, "anytime bro, if you have question just tag me"
	, "yeeah boi!! keep grinding"
	, "100% mate"
	]

rep = {
	"^hi|hello|good\s*(morning|evening|afternoon)|what'?s\s*up?|sup\s*(guys|mates|friends|fellows|yall)|he{3}e+y" :
	[ "hii"
	, "heeeeey"
	, "how are u doin?"
	, "sup mate"	
	],

	"are\s*u\s*bot\?|y\s*are\s*bot\?|he\s*is\s*bot\?|haha\s*he\s*is\s*bot" :
	[ "me?"
	, "ahaha iam bot))"
	, "iam bot reallyy"
	, "hahaha"
	, "if iam bot then who are u?"
	, "haahah am i bot?"	
	],

	"nigger|niger|cum|gay|fagot|bastard|fuck|shit|son\s*of\s*a\s*bitch|bitch|bullshit|asshole|pussy|dickhead|motherfucker|cock|ass" :
	[ "pls without swear words"
	, "can you please dont use words like this?"
	, "pls be respectful we are friendly community"
	, "we truin' to build loyal commynity, pls without swear words"	
	],

	"i'?am from europe/albania/latvia/andorra/liechtenstein/armenia/lithuania/austria/luxembourg/azerbaijan/malta/belarus/belgium/monaco/bosnia/herzegovina/montenegro/bulgaria/netherlands/croatia/norway/cyprus/poland/czech/republic/potugal/denmark/romania/estonia/finland/san marino/former/yugoslav/republic of macedonia/macedonia/serbia/france/slovakia/georgia/slovenia/germany/spain/greece/gweden/hungary/sweden/iceland/switzerland/ireland/turkey/italy/kosovo/united kingdom" :
	[ "nice place in Europe mate))"
	, "ohh, great place in europe))"
	, "I reaaly love this european place, good job!"
	, "i was there once, wonderfull place btw))"	
	],

	"i'?am\s*from\s*(afghanistan|armenia|azerbaijan|bahrain|bangladesh|bhutan|brunei|cambodia|cyprus|georgia|india|indonesia|iran|iraq|israel|japan|jordan|kazakhstan|kuwait|kyrgyzstan|laos|lebanon|malaysia|maldives|mongolia|myanmar|nepal|north\s*korea|oman|pakistan|palestine|philippines|qatar\s*saudi|arabia|singapore|south\s*korea|sri\s*lanka|syria|taiwan|tajikistan|thailand|timor-leste|turkey|turkmenistan|united\s*arab\s*emirates|uzbekistan|vietnam|yemen)" :
	[ "Nice place in asia mate))"
	, "ohh, great place in asia))"
	, "I reaaly love this asian place, good job!"
	, "i was there once, had some fun","wonderfull place btw))"
	, "shiish, like this place"
	, "cool place dude))"	
	],

	"i'?am\s*from\s*china" :
	[ "ching cheng chang chi))"
	, "listen dude : How do you know if the Chinese criminals rob your house. Everything's gone but your homework done neatly and is up to date.."
	, "What do you call a Chinese man with one leg? Tie won shu"
	, "That one awkward moment you have to go ask your Chinese neighbor if they’ve seen your dog."
	, "What did the doctor say to the chinese patient? Sum ting wong"
	, "So I asked a Chinese woman for her number, she said 'sex, sex, sex, free sex tonight.' Her friend said 'No, it’s 666-3629.'"
	],

	"i'?am\s*from\s*(ukraine|russia|moldova)" :
	[ "welcome to the club comrade"
	, "hmm... nice post soviet union place))"
	, "nice place innit?"
	, "putin is ur president???"
	, "i love salo"
	, "How does every Russian joke start? By looking over your shoulder.))"
	, "Whats the difference between a smart Russian and a unicorn? Nothing, they're both fictional characters"
	],

	"ching\s*cheng\s*chang\s*chi\)\)|lol|xd|joke|funny|haha|heheh|hmm,\s*maybe\s*couple\s*grands|i’\?m\s*down\s*like\s*the\s*floor\s*on\s*crap\s*nfts\s*lolol|i\s*cant\s*normally\s*chat\s*dude|iam\s*from\s*the\s*planet\s*earth\)\)|how\s*do\s*you\s*know\s*if\s*the\s*chinese\s*criminals\s*rob\s*your\s*house\.\s*everything'\?s\s*gone\s*but\s*your\s*homework\s*done\s*neatly\s*and\s*is\s*up\s*to\s*date\.\.|what\s*do\s*you\s*call\s*a\s*chinese\s*man\s*with\s*one\s*leg\?\s*tie\s*won\s*shu|that\s*one\s*awkward\s*moment\s*you\s*have\s*to\s*go\s*ask\s*your\s*chinese\s*neighbor\s*if\s*they’\?ve\s*seen\s*your\s*dog\.|what\s*did\s*the\s*doctor\s*say\s*to\s*the\s*chinese\s*patient\?\s*sum\s*ting\s*wong|so\s*i\s*asked\s*a\s*chinese\s*woman\s*for\s*her\s*number,\s*she\s*said\s*'\?sex,\s*sex,\s*sex,\s*free\s*sex\s*tonight\s*,'\?\s*her\s*friend\s*said\s*“no,\s*it’\?s\s*666-3629\.|how\s*does\s*every\s*russian\s*joke\s*start\?\s*by\s*looking\s*over\s*your\s*shoulder\.\)\)|whats\s*the\s*difference\s*between\s*a\s*smart\s*russian\s*and\s*a\s*unicorn\?\s*nothing,\s*they'\?re\s*both\s*fictional\s*characters" :
	[ "yeah ist funny))"
	, "nice joke, man"
	, "haha yeah, its true))"
	, "hahahaahhaha lol"
	, "haha, noway"
	, "just joking))"
	, "hahaha ok dude,"
	, "lol, its up to u mate))"
	, "hahah ok youre cool guy"
	, "ok youre real OG haha)"
	, "hahahaahh, lmao"
	, "hahahah you are rofling innit??"
	, "nice joke man ahahahaha"
	, "shhhhish, gem joke dude)"
	, "that funnu, dude"
	, "ahahah ok man, nice joke))"	
	],

	"thx|thank\s*you|thanks" :
	[ "ur welcome"
	, "of course dude"
	, "sure dude"
	, "nice man"
	, "always at your service mate)"
	, "if u have troubles just tag me man))"	
	],

	"ready\s*to\s*go\s*all\s*the\s*way\s*and\s*be\s*left\s*without\s*fingers|need\s*this\s*projectt/project|anyone\s*here\s*new\s*to\s*discord\?|no\s*sleep\s*for\s*me" :
	[ "me too bro," "hah same bro"
	, "yeee, thats true))"
	, "cant argue with u man))"
	, "absolytely yep"
	, "dude you are crazy,"
	, "no fuck** way man))",],

	"what\s*do\s*you\s*think\s*about\s*the\s*mint\s*price,\s*huh\?|\s*whats\s*the\s*price\?|price\?|hey\s*guys\s*can\s*you\s*point\s*me\s*in\s*the\s*direction\s*of\s*some\s*good\s*gaming\s*cryptos\s*(serious\s*question)" :
	[ "I dont know))," "no one knows, dude"
	, "maybe TBA.."
	, "who knows mate)"
	, "hahh, nice quesition"
	, "dont know, have u any suggestions?"
	, "hmm, maybe couple grands))"	
	],

	"how\s*are\s*(u/u\s*doing/u\s*doin/doing/doin/feelin)\??|sup|how\s*it'?s\s*(goin/going)" :
	[ "doing great and u mate?"
	, "nice dude, how about u"
	, "perfect mare. how u doin?"
	, "better and better mate))"
	, "chilling dude"
	, "iam great bro, same as u))"
	, "just having good time here)"	
	],

	"where\s*are\s*you\s*from\??|where\s*are\s*u\s*from\??" :
	[ "iam from the planet earth))"
	, "iam from europe"
	, "iam from Albania"
	, "iam from Latvia"
	, "iam from Andorra"
	, "iam from liechtenstein"
	, "iam from Armenia"
	, "iam from Lithuania"
	, "iam from Austria"
	, "iam from Luxembourg"
	, "iam from Azerbaijan"
	, "iam from Malta"
	, "iam from Belarus"
	, "iam from Belgium"
	, "iam from Monaco"
	, "iam from Bosnia"
	, "iam from Herzegovina"
	, "iam from Montenegro"
	, "iam from Bulgaria"
	, "iam from Netherlands"
	, "iam from Croatia"
	, "iam from Norway"
	, "iam from Cyprus"
	, "iam from Poland"
	, "iam from Czech"
	, "iam from Republic"
	, "iam from Portugal"
	, "iam from Denmark"
	, "iam from Romania"
	, "iam from Estonia"
	, "iam from Finland"
	, "iam from SanMarino"
	, "iam from Former"
	, "iam from Yugoslav"
	, "iam from Republic of Macedonia"
	, "iam from Macedonia"
	, "iam from Serbia"
	, "iam from France"
	, "iam from Slovakia"
	, "iam from Georgia"
	, "iam from Slovenia"
	, "iam from Germany"
	, "iam from Spain"
	, "iam from Greece"
	, "iam from Sweden"
	, "iam from Hungary"
	, "iam from Sweden"
	, "iam from Iceland"
	, "iam from Switzerland"
	, "iam from Ireland"
	, "iam from Turkey"
	, "iam from Italy"
	, "iam from Kosovo"
	, "iam from United Kingdom, and you?"	
	]
}
